<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Orta Mahalle, niversite Caddesi, No27_ba530d</name>
   <tag></tag>
   <elementGuidId>e824665b-ecd0-4abc-9ceb-29d819817f03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='GTC3MJOOBR24XU6GJGDEG12NOXID2HASYA27YSAH2DIXONPPXTQ2EIA2OXVSYU4Z:1:nhrplpipnokq']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;GTC3MJOOBR24XU6GJGDEG12NOXID2HASYA27YSAH2DIXONPPXTQ2EIA2OXVSYU4Z:1:nhrplpipnokq&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GTC3MJOOBR24XU6GJGDEG12NOXID2HASYA27YSAH2DIXONPPXTQ2EIA2OXVSYU4Z:1:nhrplpipnokq</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>deliverydestinationtype</name>
      <type>Main</type>
      <value>CUSTOMER_ADDRESS</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Mohamed Kassem  istmarina, İstanbul Kordonboyu Mh.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GLUXAddressList&quot;)/li[2]/span[@class=&quot;a-list-item&quot;]/span[@class=&quot;a-button a-button-toggle GLUX_Block a-button-focus&quot;]/span[@class=&quot;a-button-inner a-text-left a-padding-base a-size-base a-button-text&quot;]/input[@class=&quot;a-button-input&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='GTC3MJOOBR24XU6GJGDEG12NOXID2HASYA27YSAH2DIXONPPXTQ2EIA2OXVSYU4Z:1:nhrplpipnokq']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='GLUXAddressList']/li[2]/span/span/span/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/span/span/span/input</value>
   </webElementXpaths>
</WebElementEntity>
