<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>c36cb18f-9926-4bce-b04a-c56a554de91b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a-page']/div[2]/div/div/div/div/div/div/div/div[3]/div[2]/a/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Elday&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>window.uet &amp;&amp; uet.call &amp;&amp; uet(&quot;af&quot;);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://elday.org/wp-content/themes/elday/images/elday_logo_footer.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Elday</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Elday</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-page&quot;)/div[@class=&quot;a-container&quot;]/div[@class=&quot;a-row&quot;]/div[@class=&quot;a-column a-span12&quot;]/div[@class=&quot;a-row&quot;]/div[@class=&quot;make-money-tracking-wrapper&quot;]/div[@class=&quot;as-body desktop&quot;]/div[@class=&quot;border-color-squid-ink     flex-container flex-align-items-stretch flex-align-content-flex-start flex-full-width amsg-2018 border-color-squid-ink design-Sell fonts-loaded&quot;]/div[@class=&quot;border-color-squid-ink     flex-container flex-align-items-stretch flex-align-content-flex-start flex-full-width amsg-2018 border-color-squid-ink design-Sell fonts-loaded&quot;]/div[@class=&quot;border-color-squid-ink     flex-container flex-align-items-stretch flex-align-content-flex-start flex-full-width amsg-2018 border-color-squid-ink design-Sell fonts-loaded&quot;]/div[@class=&quot;border-color-squid-ink     padding-top-xmini flex-container flex-align-items-stretch flex-align-content-flex-start amsg-2018 border-color-squid-ink design-Sell fonts-loaded&quot;]/a[@class=&quot;link-container&quot;]/div[@class=&quot;border-color-squid-ink     flex-container flex-align-items-stretch flex-align-content-flex-start flex-full-width amsg-2018 border-color-squid-ink design-Sell fonts-loaded&quot;]/div[@class=&quot;image image-size-custom align-center&quot;]/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a-page']/div[2]/div/div/div/div/div/div/div/div[3]/div[2]/a/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Elday']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/a/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
