<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Container</name>
   <tag></tag>
   <elementGuidId>8708fbb7-9feb-4636-b5cb-b702584c1ef4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='YOUTUBEPOPUP']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>max-width-800px popup-container  </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Amazon.com.tr Satıcı Eğitim Programı artık YouTube’daSatıcı Eğitim Programı YouTube video platformu sayesinde mevcut ya da potansiyel satış ortaklarımız, Amazon.com.tr süreçlerini daha iyi anlayarak gelişim süreçlerine ivme kazandırabilecek, işletmelerini Amazon aracılığıyla büyütebilecekler.Hızlı ve etkili şekilde ürün listeleme, online satış için kullanılan temel araç ve uygulamalar, Amazon Lojistik (FBA), Global Satış ve diğer Amazon hizmetleri hakkında detaylı video içeriklerine erişin.YouTube kanalımıza erişmek için tıklayın</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;YOUTUBEPOPUP&quot;)/div[@class=&quot;popup&quot;]/div[@class=&quot;max-width-800px popup-container&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='YOUTUBEPOPUP']/div/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='✕'])[1]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2018 Amazon.com, Inc. veya bağlı ortaklıklar. Her hakkı saklıdır'])[1]/following::div[8]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div[2]</value>
   </webElementXpaths>
</WebElementEntity>
