<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AppStore</name>
   <tag></tag>
   <elementGuidId>52567625-0a3e-481d-b0d8-2a05e91b5ae4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a-page']/div[2]/div/div/div/div/div/div/div/div/div[2]/div[2]/div[3]/div[2]/a/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/G/02/mobile/ALP/Download_app_store_TR.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-page&quot;)/div[@class=&quot;a-container&quot;]/div[@class=&quot;a-row&quot;]/div[@class=&quot;a-column a-span12&quot;]/div[@class=&quot;a-row&quot;]/div[@class=&quot;make-money-tracking-wrapper&quot;]/div[@class=&quot;desktop&quot;]/div[@class=&quot;flex-container flex-align-items-stretch flex-align-content-flex-start flex-full-width amsg-2018 border-color-transparent fonts-loaded&quot;]/div[@class=&quot;flex-container flex-align-items-stretch flex-align-content-flex-start flex-full-width amsg-2018 border-color-transparent fonts-loaded&quot;]/div[@class=&quot;bg-no-repeat     flex-container flex-align-items-stretch flex-align-content-flex-start flex-full-width amsg-2018 border-color-transparent fonts-loaded&quot;]/div[@class=&quot;flex-container flex-align-items-stretch flex-align-content-flex-start flex-full-width amsg-2018 border-color-transparent fonts-loaded&quot;]/div[@class=&quot;flex-container flex-align-items-stretch flex-align-content-flex-start amsg-2018 border-color-transparent fonts-loaded&quot;]/div[@class=&quot;padding-left-base padding-top-base flex-container flex-align-items-stretch flex-align-content-flex-start flex-full-width amsg-2018 border-color-transparent fonts-loaded&quot;]/div[@class=&quot;padding-left-xlarge flex-container flex-align-items-stretch flex-align-content-flex-start amsg-2018 border-color-transparent fonts-loaded&quot;]/a[@class=&quot;link-container&quot;]/div[@class=&quot;flex-container flex-align-items-stretch flex-align-content-flex-start flex-full-width amsg-2018 border-color-transparent fonts-loaded&quot;]/div[@class=&quot;image align-start&quot;]/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a-page']/div[2]/div/div/div/div/div/div/div/div/div[2]/div[2]/div[3]/div[2]/a/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://m.media-amazon.com/images/G/02/mobile/ALP/Download_app_store_TR.png')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
