<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Salk ve Bakm Kategorisinde ok Satanlar _cce84e</name>
   <tag></tag>
   <elementGuidId>f8b58602-a53a-4ced-bfc1-3a9ac7045a43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zg_left_col1']/div/div[3]/div/div[2]/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Oral-B Cross Action Diş Fırçası Yedek Başlığı, 2 Adet</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images-na.ssl-images-amazon.com/images/I/71gfofTCLTL._AC_UL320_SR320,320_.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-dynamic-image p13n-sc-dynamic-image</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>160</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>160</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-a-dynamic-image</name>
      <type>Main</type>
      <value>{&quot;https://images-na.ssl-images-amazon.com/images/I/71gfofTCLTL._AC_UL320_SR320,320_.jpg&quot;:[320,320],&quot;https://images-na.ssl-images-amazon.com/images/I/71gfofTCLTL._AC_UL160_SR160,160_.jpg&quot;:[160,160],&quot;https://images-na.ssl-images-amazon.com/images/I/71gfofTCLTL._AC_UL480_SR480,480_.jpg&quot;:[480,480]}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zg_left_col1&quot;)/div[@class=&quot;zg_homeWidget&quot;]/div[@class=&quot;zg_item zg_homeWidgetItem&quot;]/div[@class=&quot;zg_rankInfo&quot;]/div[@class=&quot;a-section a-spacing-none p13n-asin&quot;]/a[@class=&quot;a-link-normal&quot;]/div[@class=&quot;a-section a-spacing-mini&quot;]/img[@class=&quot;a-dynamic-image p13n-sc-dynamic-image&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zg_left_col1']/div/div[3]/div/div[2]/a/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Oral-B Cross Action Diş Fırçası Yedek Başlığı, 2 Adet']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/a/div/img</value>
   </webElementXpaths>
</WebElementEntity>
