<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bu adresi kullan</name>
   <tag></tag>
   <elementGuidId>e494737c-59af-40f6-8fa8-3634065fdfc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='address-book-entry-1']/div[2]/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>page-spinner-show</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-declarative a-button-text </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/gp/buy/addressselect/handlers/continue.html/ref=ox_shipaddress_ship_to_this_2?ie=UTF8&amp;action=select-shipping&amp;addressID=GTC3MJOOBR24XU6GJGDEG12NOXID2HASYA27YSAH2DIXONPPXTQ2EIA2OXVSYU4Z&amp;enableDeliveryPreferences=&amp;fromAnywhere=0&amp;numberOfDistinctItems=2&amp;purchaseId=404-2089261-9221920&amp;requestToken=&amp;hasWorkingJavascript=1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Bu adresi kullan 
                    </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address-book-entry-1&quot;)/div[@class=&quot;ship-to-this-address a-button a-button-primary a-button-span12 a-spacing-medium   a-button-focus&quot;]/span[@class=&quot;a-button-inner&quot;]/a[@class=&quot;a-declarative a-button-text&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='address-book-entry-1']/div[2]/span/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Bu adresi kullan')])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Türkiye'])[2]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Düzenle'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sil'])[1]/preceding::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/gp/buy/addressselect/handlers/continue.html/ref=ox_shipaddress_ship_to_this_2?ie=UTF8&amp;action=select-shipping&amp;addressID=GTC3MJOOBR24XU6GJGDEG12NOXID2HASYA27YSAH2DIXONPPXTQ2EIA2OXVSYU4Z&amp;enableDeliveryPreferences=&amp;fromAnywhere=0&amp;numberOfDistinctItems=2&amp;purchaseId=404-2089261-9221920&amp;requestToken=&amp;hasWorkingJavascript=1')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/span/a</value>
   </webElementXpaths>
</WebElementEntity>
