<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>30Days</name>
   <tag></tag>
   <elementGuidId>5d92ca9b-cf84-4c06-ada3-072439864abf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;dvm_MLP_ROE_Canc_4&quot;]/div/div[2]/a/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dv-overlay</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dvm_MLP_tr_Join_1&quot;)/div[@class=&quot;dv-safe-content&quot;]/div[@class=&quot;dv-row-item dv-copy dv-push-right&quot;]/div[@class=&quot;dv-button-wrapper&quot;]/a[@class=&quot;dv-copy-button&quot;]/span[@class=&quot;dv-overlay&quot;]</value>
   </webElementProperties>
</WebElementEntity>
