<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_imdi izleyin, istediiniz zaman iptal edin._dv-overlay</name>
   <tag></tag>
   <elementGuidId>47aad5d7-bdba-41d7-9ff4-442de1c737af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dvm_MLP_ROE_Canc_4']/div/div[2]/a/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.dv-row-item.dv-copy.dv-push-right > a.dv-copy-button > span.dv-overlay</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dv-overlay</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dvm_MLP_ROE_Canc_4&quot;)/div[@class=&quot;dv-safe-content&quot;]/div[@class=&quot;dv-row-item dv-copy dv-push-right&quot;]/a[@class=&quot;dv-copy-button&quot;]/span[@class=&quot;dv-overlay&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dvm_MLP_ROE_Canc_4']/div/div[2]/a/span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/a/span[2]</value>
   </webElementXpaths>
</WebElementEntity>
