<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>6e8ac4d4-5e26-47e2-8de4-962f95a4550b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='AUQODInYNXHtVuc4dIAJiA']/div/div/span/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Amazon Prime Üyelerine Özel BEDAVA aynı gün ve ertesi gün teslimat tüm hızıyla kesintisiz devam ediyor. hemen dene&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Amazon Prime Üyelerine Özel BEDAVA aynı gün ve ertesi gün teslimat tüm hızıyla kesintisiz devam ediyor. hemen dene</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images-eu.ssl-images-amazon.com/images/G/41/TR-hq/2021/COVID/LockdownDEX/NonPrime/FOR_NON_PRIME_MEMBERS_COVID_LOCKDOWN_MESSAGING_1500x600._CB670989722_.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>600px</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1500px</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-a-hires</name>
      <type>Main</type>
      <value>https://images-eu.ssl-images-amazon.com/images/G/41/TR-hq/2021/COVID/LockdownDEX/NonPrime/FOR_NON_PRIME_MEMBERS_COVID_LOCKDOWN_MESSAGING_3000x1200._CB670989722_.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AUQODInYNXHtVuc4dIAJiA&quot;)/div[@class=&quot;cropped-image-map-size&quot;]/div[@class=&quot;cropped-image-map-center-alignment&quot;]/span[1]/a[@class=&quot;a-link-normal aok-inline-block&quot;]/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AUQODInYNXHtVuc4dIAJiA']/div/div/span/a/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Amazon Prime Üyelerine Özel BEDAVA aynı gün ve ertesi gün teslimat tüm hızıyla kesintisiz devam ediyor. hemen dene']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div/div/div/span/a/img</value>
   </webElementXpaths>
</WebElementEntity>
