<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Robot sprgeleri kefedin_landscape-image</name>
   <tag></tag>
   <elementGuidId>24b0522e-3873-46a9-bfe7-fb0383d95fa9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='YxSNG4YMfu5mQraPEeIvBA']/div[2]/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#YxSNG4YMfu5mQraPEeIvBA > div.a-cardui-body > a.a-link-normal.center-image.aok-block.image-window > div.a-section.a-spacing-none.fluid-image-container > img.landscape-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Robot süpürgeleri keşfedin</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images-eu.ssl-images-amazon.com/images/G/41/TR-hq/2021/Iltan/Kitchen/Evergreen/XCM_Manual_1309834_1579922_TR_TR_DEALS_tr_gw_pc_single_category_card_2x_tr_tr_3707857_379x304_1X_tr_TR._SY304_CB658880150_.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>landscape-image</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-a-hires</name>
      <type>Main</type>
      <value>https://images-eu.ssl-images-amazon.com/images/G/41/TR-hq/2021/Iltan/Kitchen/Evergreen/XCM_Manual_1309834_1579922_TR_TR_DEALS_tr_gw_pc_single_category_card_2x_tr_tr_3707857_758x608_2X_tr_TR._SY608_CB658880150_.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;YxSNG4YMfu5mQraPEeIvBA&quot;)/div[@class=&quot;a-cardui-body&quot;]/a[@class=&quot;a-link-normal center-image aok-block image-window&quot;]/div[@class=&quot;a-section a-spacing-none fluid-image-container&quot;]/img[@class=&quot;landscape-image&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='YxSNG4YMfu5mQraPEeIvBA']/div[2]/a/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Robot süpürgeleri keşfedin']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/a/div/img</value>
   </webElementXpaths>
</WebElementEntity>
