<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>ba4bad1b-47b4-4c35-8eaa-adec12276f39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='5tv4jwTJFCxiP1MZb6-zgw']/div/div/span/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Outlet reyonu: stok fazlası yüzlerce üründe %20 ve üzeri indirim&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Outlet reyonu: stok fazlası yüzlerce üründe %20 ve üzeri indirim</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images-eu.ssl-images-amazon.com/images/G/41/TR-hq/2021/CE-SM/Outlet/NewHomepage/TR_21_OUTLET_STORE_DesktopHero_Template_1500x600_w._CB655856563_.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>600px</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1500px</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-a-hires</name>
      <type>Main</type>
      <value>https://images-eu.ssl-images-amazon.com/images/G/41/TR-hq/2021/CE-SM/Outlet/NewHomepage/TR_21_OUTLET_STORE_DesktopHero_Template_3000x1200_w._CB655856563_.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;5tv4jwTJFCxiP1MZb6-zgw&quot;)/div[@class=&quot;cropped-image-map-size&quot;]/div[@class=&quot;cropped-image-map-center-alignment&quot;]/span[1]/a[@class=&quot;a-link-normal aok-inline-block&quot;]/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='5tv4jwTJFCxiP1MZb6-zgw']/div/div/span/a/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Outlet reyonu: stok fazlası yüzlerce üründe %20 ve üzeri indirim']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div/div/div/span/a/img</value>
   </webElementXpaths>
</WebElementEntity>
